"""create raw_signals table

Revision ID: 70a69f90e052
Revises: 
Create Date: 2025-12-26 01:02:37.101377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a69f90e052'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Enum('log', 'trace', 'metric', name='signaltypeenum'), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_signals_service_name'), 'raw_signals', ['service_name'], unique=False)
    op.create_index(op.f('ix_raw_signals_signal_type'), 'raw_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_raw_signals_timestamp'), 'raw_signals', ['timestamp'], unique=False)
    op.create_index(op.f('ix_raw_signals_trace_id'), 'raw_signals', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_signals_trace_id'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_timestamp'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_signal_type'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_service_name'), table_name='raw_signals')
    op.drop_table('raw_signals')
    # ### end Alembic commands ###
